---
- hosts: all
  become: true
  tasks:
    - name: Install apache2 and php package and misc
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - mc
          - htop
          - vim-nox
        state: latest
        update_cache: true
