---
- hosts: all
  become: true
  pre_tasks:
    - name: Update repo cache
      tags: always
      apt:
        update_cache: yes
      changed_when: false
- hosts: all
  become: true
  tasks:
    - name: Add ssh key for simone
      tags: always
      authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL6EK3LY1zbhIjCWe4bJPu+cROR3V1Z24Mi/JM4wZtS6 jak3b@wintermute"

- hosts: web_servers
  become: true
  tasks:
    - name: Install apache2 and php package and misc
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest

    - name: Copy default html file for site
      tags: apache,apache2,ubuntu
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb package
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest

- hosts: file_servers
  become: true
  tasks:
    - name: Install samba
      tags: samba
      package:
        name: samba
        state: latest
